### ISSUE TITLE
Is this done?

### ISSUE THREAD

**Issue by Kerbal-Man** [Addy771/MIDI-to-MP3#1]
Is this project at the point where i can run it and it work?
What all packages do I need?
What args does it take?

**Comment by Addy771** [comment]
As far as I can remember, pygame is the only package you should need to add. It doesn't take any arguments, when you run the script it will try to convert all the midi files in the script's folder (and any subfolders)

**Comment by Kerbal-Man** [comment]
Ok thanks i got it working, but this kinda sucks and is a terrible way to convert midi to mp3

**Comment by Addy771** [comment]
Why don't you make a better solution instead of writing useless comments?
